# Generated by Django 3.1.7 on 2021-05-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit',
            field=models.TextField(default=None),
        ),
    ]
